<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>

		<PackageId>Rehber.Core.Persistence</PackageId>
		<Version>1.0.0</Version>
		<Authors>Rehber</Authors>
		<Company>Sirket Adiniz</Company>
		<Description>Uygulamanın temel core persistence katmanı için paylaşılan kütüphane.</Description>
		<PackageLicenseExpression>MIT</PackageLicenseExpression>
		<PackageRequireLicenseAcceptance>false</PackageRequireLicenseAcceptance>
		<PackageTags>core persistence common shared</PackageTags>
		<PackageOutputPath>../../nupkgs</PackageOutputPath>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="8.0.8" />
		<PackageReference Include="Microsoft.EntityFrameworkCore" Version="8.0.8" />
	</ItemGroup>

</Project>
