<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>

	<DocumentationFile>bin\$(Configuration)\$(TargetFramework)\$(AssemblyName).xml</DocumentationFile>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Core.Application\Core.Application.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Adapters\Http\ProblemDetails\" />
    <Folder Include="Exceptions\" />
    <Folder Include="Constants\" />
    <Folder Include="Extensions\Types\" />
    <Folder Include="Persistence\Contexts\" />
    <Folder Include="Services\Logging\" />
    <Folder Include="Services\Caching\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="8.0.8" />
  </ItemGroup>

</Project>
